name: citizen_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#  intl: ^0.16.1
#  flutter_svg: ^0.18.0
#  pattern_formatter: ^1.0.2

  intl: ^0.17.0
  pattern_formatter: ^2.0.0
  flutter_svg: ^0.19.3

  #animated_bottom_navigation_bar: ^0.2.1
  #flutter_appavailability: ^0.0.21
  image_picker: 0.6.6+4
  cloud_firestore: ^0.14.1+3
  firebase_storage: 5.0.0
  # Service locator
  get_it: ^5.0.1

  # Bloc for state management
  bloc: ^6.0.3
  flutter_bloc: ^6.1.1
  flutter_dotenv: ^2.1.0
  #qrscan: ^0.2.22
  cached_network_image: ^2.5.1

  # Value equality
  equatable: ^1.2.5

  # Functional programming thingies
  dartz: ^0.8.9

  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+3

  # Local cache
  shared_preferences: ^0.5.6

  rxdart: ^0.24.1
  #phone
  url_launcher: ^5.7.10

  # UI
  skeleton_text: ^1.0.0
  skeleton_animation: ^0.0.3
  shimmer: ^1.1.2
  fluttertoast: ^7.1.6

  flutter_rating_bar: ^3.2.0+1
  google_fonts: ^1.1.1
  flutter_slidable: ^0.5.7
  carousel_slider: ^2.3.1
  #readmore: ^1.0.1
  sizer: ^1.1.8
  flutter_native_splash: ^0.2.7
  #flutter_linkify: 4.0.0
  #flutter_barcode_scanner: ^1.0.2
  qr_code_scanner: ^0.0.12
  vibration: ^1.7.3

  #WebView
  #webview_flutter: ^1.0.7
  flutter_cached_pdfview: ^0.3.5
  #pdf: ^3.1.0
  flutter_webview_plugin: ^0.3.11

  # request
  permission_handler: ^4.4.0
  dio: ^3.0.10

  # Media
  #media_picker_builder: ^1.3.2
  #multi_image_picker: ^4.7.15
  flutter_absolute_path: ^1.0.6
  lazy_load_scrollview: ^1.2.0
  #video_player: ^1.0.1
  flutter_spinkit: ^4.1.2
  image_gallery_saver: ^1.6.7
  transparent_image: ^1.0.0
  photo_view: ^0.10.3
  #image_picker: ^0.6.7+14
  flutter_downloader: ^1.5.2
  chewie: ^0.12.0
  ext_storage: ^1.0.3
  #thumbnails: ^1.0.1

  # Path
  path_provider: ^1.6.24
  path: ^1.7.0

  # Maps
  #vtmap_gl: ^1.1.2
  #location: ^2.5.3
  share: ^0.6.5+4

  # SMS
  #sms_autofill: ^1.2.6
  #sms: ^0.2.4
  sleek_circular_slider: ^1.2.0+web
  cupertino_icons: ^1.0.0
  route_transitions: ^1.0.2
  flutter_staggered_animations: ^0.1.3

  #Function
  recase: ^3.0.1
  package_info: ^0.4.3+2
  awesome_dialog: ^1.2.1
  #pin_code_fields: ^6.0.1
  platform_device_id: ^0.1.3

  #text
  auto_size_text: ^2.1.0

  # Firebase
  firebase_core: ^0.5.0
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^3.0.2
  #firebase_crashlytics: ^0.2.4
  #http_proxy: ^1.1.0
  #video_player: ^1.0.1
  #video_thumbnail: ^0.2.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  #mockito: ^4.1.1
  flutter_launcher_icons: ^0.8.1
  #local_auth: ^0.6.3+5

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/launcher/ic_launcher.png"
  image_path_android: "assets/launcher/ic_launcher.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/launcher/
    - lang/vi.json
    - lang/en.json
flutter_intl:
  enabled: true
flutter_native_splash:
  image: assets/images/splash.png
  color: "#01A7A3"
  fill: true